//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAccount.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccountResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcAccount.Resources.AccountResources", typeof(AccountResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change email address.
        /// </summary>
        internal static string Links_ChangeEmail {
            get {
                return ResourceManager.GetString("Links_ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string Links_ChangePassword {
            get {
                return ResourceManager.GetString("Links_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t access your account?.
        /// </summary>
        internal static string Links_Recovery {
            get {
                return ResourceManager.GetString("Links_Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to My account.
        /// </summary>
        internal static string Links_ReturnToIndex {
            get {
                return ResourceManager.GetString("Links_ReturnToIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Links_SignIn {
            get {
                return ResourceManager.GetString("Links_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string Links_SignOut {
            get {
                return ResourceManager.GetString("Links_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enter new password.
        /// </summary>
        internal static string Model_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("Model_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string Model_CurrentPassword {
            get {
                return ResourceManager.GetString("Model_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Model_Email {
            get {
                return ResourceManager.GetString("Model_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email change notification.
        /// </summary>
        internal static string Model_EmailChangeNotificationMessageSubject {
            get {
                return ResourceManager.GetString("Model_EmailChangeNotificationMessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email change verification.
        /// </summary>
        internal static string Model_EmailChangeVerificationMessageSubject {
            get {
                return ResourceManager.GetString("Model_EmailChangeVerificationMessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New email address.
        /// </summary>
        internal static string Model_NewEmail {
            get {
                return ResourceManager.GetString("Model_NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string Model_NewPassword {
            get {
                return ResourceManager.GetString("Model_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Model_Password {
            get {
                return ResourceManager.GetString("Model_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Assistance.
        /// </summary>
        internal static string Model_PasswordResetVerificationMessageSubject {
            get {
                return ResourceManager.GetString("Model_PasswordResetVerificationMessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay signed in.
        /// </summary>
        internal static string Model_RememberMe {
            get {
                return ResourceManager.GetString("Model_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Model_Username {
            get {
                return ResourceManager.GetString("Model_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {1} is incorrect..
        /// </summary>
        internal static string Validation_CurrentPasswordIncorrect {
            get {
                return ResourceManager.GetString("Validation_CurrentPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with email &apos;{0}&apos; already exists..
        /// </summary>
        internal static string Validation_EmailAlreadyExists {
            get {
                return ResourceManager.GetString("Validation_EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is invalid..
        /// </summary>
        internal static string Validation_EmailPattern {
            get {
                return ResourceManager.GetString("Validation_EmailPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the max. number of invalid attempts, you can try again in {0} minutes..
        /// </summary>
        internal static string Validation_MaxInvalidSignInAttempts {
            get {
                return ResourceManager.GetString("Validation_MaxInvalidSignInAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We don&apos;t have your email address in our records, your request cannot be completed..
        /// </summary>
        internal static string Validation_MissingEmail {
            get {
                return ResourceManager.GetString("Validation_MissingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot authenticate..
        /// </summary>
        internal static string Validation_MissingPasswordCannotAuthenticate {
            get {
                return ResourceManager.GetString("Validation_MissingPasswordCannotAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {1} must be different from the current one..
        /// </summary>
        internal static string Validation_NewEmailSameAsCurrent {
            get {
                return ResourceManager.GetString("Validation_NewEmailSameAsCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        internal static string Validation_PasswordsNotMatch {
            get {
                return ResourceManager.GetString("Validation_PasswordsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field cannot be left blank..
        /// </summary>
        internal static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} cannot have more than {1} characters..
        /// </summary>
        internal static string Validation_StringLength {
            get {
                return ResourceManager.GetString("Validation_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must have between {2} and  {1} characters..
        /// </summary>
        internal static string Validation_StringLengthWithMin {
            get {
                return ResourceManager.GetString("Validation_StringLengthWithMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is disabled..
        /// </summary>
        internal static string Validation_UserDisabled {
            get {
                return ResourceManager.GetString("Validation_UserDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string Validation_UserNotExist {
            get {
                return ResourceManager.GetString("Validation_UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and password do not match..
        /// </summary>
        internal static string Validation_UserPassNotMatch {
            get {
                return ResourceManager.GetString("Validation_UserPassNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account options.
        /// </summary>
        internal static string Views_Account_Index_Title {
            get {
                return ResourceManager.GetString("Views_Account_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Views_Auth_SignIn_Title {
            get {
                return ResourceManager.GetString("Views_Auth_SignIn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Views_Cancel {
            get {
                return ResourceManager.GetString("Views_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change email address.
        /// </summary>
        internal static string Views_Email_Change_Change_Title {
            get {
                return ResourceManager.GetString("Views_Email_Change_Change_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new email address has been saved..
        /// </summary>
        internal static string Views_Email_Change_Saved_Message {
            get {
                return ResourceManager.GetString("Views_Email_Change_Saved_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email saved.
        /// </summary>
        internal static string Views_Email_Change_Saved_Title {
            get {
                return ResourceManager.GetString("Views_Email_Change_Saved_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To confirm your email address change, follow the instructions sent to your &lt;strong&gt;{0}&lt;/strong&gt; email address..
        /// </summary>
        internal static string Views_Email_Change_VerificationSent_Message {
            get {
                return ResourceManager.GetString("Views_Email_Change_VerificationSent_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Email Sent.
        /// </summary>
        internal static string Views_Email_Change_VerificationSent_Title {
            get {
                return ResourceManager.GetString("Views_Email_Change_VerificationSent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string Views_Password_Change_Change_Title {
            get {
                return ResourceManager.GetString("Views_Password_Change_Change_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password has been saved..
        /// </summary>
        internal static string Views_Password_Change_Saved_Message {
            get {
                return ResourceManager.GetString("Views_Password_Change_Saved_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password saved.
        /// </summary>
        internal static string Views_Password_Change_Saved_Title {
            get {
                return ResourceManager.GetString("Views_Password_Change_Saved_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset..
        /// </summary>
        internal static string Views_Password_Reset_Done_Message {
            get {
                return ResourceManager.GetString("Views_Password_Reset_Done_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset.
        /// </summary>
        internal static string Views_Password_Reset_Done_Title {
            get {
                return ResourceManager.GetString("Views_Password_Reset_Done_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your new password and enter it below..
        /// </summary>
        internal static string Views_Password_Reset_Finish_Message {
            get {
                return ResourceManager.GetString("Views_Password_Reset_Finish_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string Views_Password_Reset_Finish_Title {
            get {
                return ResourceManager.GetString("Views_Password_Reset_Finish_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To reset your password, enter your {0}..
        /// </summary>
        internal static string Views_Password_Reset_Reset_Message {
            get {
                return ResourceManager.GetString("Views_Password_Reset_Reset_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string Views_Password_Reset_Reset_Title {
            get {
                return ResourceManager.GetString("Views_Password_Reset_Reset_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To reset your password, follow the instructions sent to your &lt;strong&gt;{0}&lt;/strong&gt; email address..
        /// </summary>
        internal static string Views_Password_Reset_VerificationSent_Message {
            get {
                return ResourceManager.GetString("Views_Password_Reset_VerificationSent_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Email Sent.
        /// </summary>
        internal static string Views_Password_Reset_VerificationSent_Title {
            get {
                return ResourceManager.GetString("Views_Password_Reset_VerificationSent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Views_Submit {
            get {
                return ResourceManager.GetString("Views_Submit", resourceCulture);
            }
        }
    }
}
