//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Web;

namespace MvcAccount {
   
   /// <summary>
   /// Provides access to localized strings.
   /// </summary>
   public static partial class AccountResources {

      /// <summary>
      /// Looks up a localized string similar to 'Change password'.
      /// </summary>
      public static string Links_ChangePassword {
         get { return GetResource(Keys.Links_ChangePassword); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'My account'.
      /// </summary>
      public static string Links_Index {
         get { return GetResource(Keys.Links_Index); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Can't access your account?'.
      /// </summary>
      public static string Links_Recovery {
         get { return GetResource(Keys.Links_Recovery); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Sign in'.
      /// </summary>
      public static string Links_SignIn {
         get { return GetResource(Keys.Links_SignIn); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Sign out'.
      /// </summary>
      public static string Links_SignOut {
         get { return GetResource(Keys.Links_SignOut); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'The {1} is incorrect.'.
      /// </summary>
      public static string Validation_CurrentPasswordIncorrect {
         get { return GetResource(Keys.Validation_CurrentPasswordIncorrect); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'User with email '{0}' already exists.'.
      /// </summary>
      public static string Validation_EmailAlreadyExists {
         get { return GetResource(Keys.Validation_EmailAlreadyExists); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'You have reached the max. number of invalid attempts, you can try again in {0} minutes.'.
      /// </summary>
      public static string Validation_MaxInvalidSignInAttempts {
         get { return GetResource(Keys.Validation_MaxInvalidSignInAttempts); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'We don't have your email address in our records, your request cannot be completed.'.
      /// </summary>
      public static string Validation_MissingEmail {
         get { return GetResource(Keys.Validation_MissingEmail); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Cannot authenticate.'.
      /// </summary>
      public static string Validation_MissingPasswordCannotAuthenticate {
         get { return GetResource(Keys.Validation_MissingPasswordCannotAuthenticate); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Passwords do not match.'.
      /// </summary>
      public static string Validation_PasswordsNotMatch {
         get { return GetResource(Keys.Validation_PasswordsNotMatch); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Required field cannot be left blank.'.
      /// </summary>
      public static string Validation_Required {
         get { return GetResource(Keys.Validation_Required); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Your account is disabled.'.
      /// </summary>
      public static string Validation_UserDisabled {
         get { return GetResource(Keys.Validation_UserDisabled); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'User '{0}' does not exist.'.
      /// </summary>
      public static string Validation_UserNotExist {
         get { return GetResource(Keys.Validation_UserNotExist); }
      }

      /// <summary>
      /// Looks up a localized string similar to '{0} and password do not match.'.
      /// </summary>
      public static string Validation_UserPassNotMatch {
         get { return GetResource(Keys.Validation_UserPassNotMatch); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Change password'.
      /// </summary>
      public static string Views_Password_Change_Change_Title {
         get { return GetResource(Keys.Views_Password_Change_Change_Title); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Account options'.
      /// </summary>
      public static string Views_Account_Index_Title {
         get { return GetResource(Keys.Views_Account_Index_Title); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Your password has been reset.'.
      /// </summary>
      public static string Views_Password_Reset_Done_Message {
         get { return GetResource(Keys.Views_Password_Reset_Done_Message); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Password Reset'.
      /// </summary>
      public static string Views_Password_Reset_Done_Title {
         get { return GetResource(Keys.Views_Password_Reset_Done_Title); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Your new password has been saved.'.
      /// </summary>
      public static string Views_Password_Change_Saved_Message {
         get { return GetResource(Keys.Views_Password_Change_Saved_Message); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Password saved'.
      /// </summary>
      public static string Views_Password_Change_Saved_Title {
         get { return GetResource(Keys.Views_Password_Change_Saved_Title); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'To reset your password, follow the instructions sent to your <strong>{0}</strong> email address.'.
      /// </summary>
      public static string Views_Password_Reset_VerificationSent_Message {
         get { return GetResource(Keys.Views_Password_Reset_VerificationSent_Message); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Recovery Email Sent'.
      /// </summary>
      public static string Views_Password_Reset_VerificationSent_Title {
         get { return GetResource(Keys.Views_Password_Reset_VerificationSent_Title); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'To reset your password, enter your {0}.'.
      /// </summary>
      public static string Views_Password_Reset_Reset_Message {
         get { return GetResource(Keys.Views_Password_Reset_Reset_Message); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Forgot your password?'.
      /// </summary>
      public static string Views_Password_Reset_Reset_Title {
         get { return GetResource(Keys.Views_Password_Reset_Reset_Title); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Select your new password and enter it below.'.
      /// </summary>
      public static string Views_Password_Reset_Finish_Message {
         get { return GetResource(Keys.Views_Password_Reset_Finish_Message); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Reset Password'.
      /// </summary>
      public static string Views_Password_Reset_Finish_Title {
         get { return GetResource(Keys.Views_Password_Reset_Finish_Title); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Sign in'.
      /// </summary>
      public static string Views_Auth_SignIn_Title {
         get { return GetResource(Keys.Views_Auth_SignIn_Title); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Submit'.
      /// </summary>
      public static string Views_Submit {
         get { return GetResource(Keys.Views_Submit); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Re-enter new password'.
      /// </summary>
      public static string Model_ConfirmNewPassword {
         get { return GetResource(Keys.Model_ConfirmNewPassword); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Current password'.
      /// </summary>
      public static string Model_CurrentPassword {
         get { return GetResource(Keys.Model_CurrentPassword); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Email'.
      /// </summary>
      public static string Model_Email {
         get { return GetResource(Keys.Model_Email); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'New password'.
      /// </summary>
      public static string Model_NewPassword {
         get { return GetResource(Keys.Model_NewPassword); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Password'.
      /// </summary>
      public static string Model_Password {
         get { return GetResource(Keys.Model_Password); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Stay signed in'.
      /// </summary>
      public static string Model_RememberMe {
         get { return GetResource(Keys.Model_RememberMe); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Password Assistance'.
      /// </summary>
      public static string Model_ResetPasswordMessageSubject {
         get { return GetResource(Keys.Model_ResetPasswordMessageSubject); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Username'.
      /// </summary>
      public static string Model_Username {
         get { return GetResource(Keys.Model_Username); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'New email address'.
      /// </summary>
      public static string Model_NewEmail {
         get { return GetResource(Keys.Model_NewEmail); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'The {0} is invalid.'.
      /// </summary>
      public static string Validation_EmailPattern {
         get { return GetResource(Keys.Validation_EmailPattern); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'The {0} cannot have more than {1} characters.'.
      /// </summary>
      public static string Validation_StringLength {
         get { return GetResource(Keys.Validation_StringLength); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'The {0} must have between {2} and  {1} characters.'.
      /// </summary>
      public static string Validation_StringLengthWithMin {
         get { return GetResource(Keys.Validation_StringLengthWithMin); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Email change notification'.
      /// </summary>
      public static string Model_EmailChangeNotificationMessageSubject {
         get { return GetResource(Keys.Model_EmailChangeNotificationMessageSubject); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Email change verification'.
      /// </summary>
      public static string Model_EmailChangeVerificationMessageSubject {
         get { return GetResource(Keys.Model_EmailChangeVerificationMessageSubject); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Email address verification'.
      /// </summary>
      public static string Model_EmailVerificationMessageSubject {
         get { return GetResource(Keys.Model_EmailVerificationMessageSubject); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'The {1} must be different from the current one.'.
      /// </summary>
      public static string Validation_NewEmailSameAsCurrent {
         get { return GetResource(Keys.Validation_NewEmailSameAsCurrent); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Change email address'.
      /// </summary>
      public static string Links_ChangeEmail {
         get { return GetResource(Keys.Links_ChangeEmail); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Change email address'.
      /// </summary>
      public static string Views_Email_Change_Change_Title {
         get { return GetResource(Keys.Views_Email_Change_Change_Title); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Your new email address has been saved.'.
      /// </summary>
      public static string Views_Email_Change_Saved_Message {
         get { return GetResource(Keys.Views_Email_Change_Saved_Message); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Email saved'.
      /// </summary>
      public static string Views_Email_Change_Saved_Title {
         get { return GetResource(Keys.Views_Email_Change_Saved_Title); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Go to {0}'.
      /// </summary>
      public static string Views_GoTo {
         get { return GetResource(Keys.Views_GoTo); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'To confirm your email address change, follow the instructions sent to your <strong>{0}</strong> email address.'.
      /// </summary>
      public static string Views_Email_Change_VerificationSent_Message {
         get { return GetResource(Keys.Views_Email_Change_VerificationSent_Message); }
      }

      /// <summary>
      /// Looks up a localized string similar to 'Verification Email Sent'.
      /// </summary>
      public static string Views_Email_Change_VerificationSent_Title {
         get { return GetResource(Keys.Views_Email_Change_VerificationSent_Title); }
      }
      
      internal static class Keys {
      
         public const string
            Links_ChangePassword = "Links_ChangePassword",
            Links_Index = "Links_Index",
            Links_Recovery = "Links_Recovery",
            Links_SignIn = "Links_SignIn",
            Links_SignOut = "Links_SignOut",
            Validation_CurrentPasswordIncorrect = "Validation_CurrentPasswordIncorrect",
            Validation_EmailAlreadyExists = "Validation_EmailAlreadyExists",
            Validation_MaxInvalidSignInAttempts = "Validation_MaxInvalidSignInAttempts",
            Validation_MissingEmail = "Validation_MissingEmail",
            Validation_MissingPasswordCannotAuthenticate = "Validation_MissingPasswordCannotAuthenticate",
            Validation_PasswordsNotMatch = "Validation_PasswordsNotMatch",
            Validation_Required = "Validation_Required",
            Validation_UserDisabled = "Validation_UserDisabled",
            Validation_UserNotExist = "Validation_UserNotExist",
            Validation_UserPassNotMatch = "Validation_UserPassNotMatch",
            Views_Password_Change_Change_Title = "Views_Password_Change_Change_Title",
            Views_Account_Index_Title = "Views_Account_Index_Title",
            Views_Password_Reset_Done_Message = "Views_Password_Reset_Done_Message",
            Views_Password_Reset_Done_Title = "Views_Password_Reset_Done_Title",
            Views_Password_Change_Saved_Message = "Views_Password_Change_Saved_Message",
            Views_Password_Change_Saved_Title = "Views_Password_Change_Saved_Title",
            Views_Password_Reset_VerificationSent_Message = "Views_Password_Reset_VerificationSent_Message",
            Views_Password_Reset_VerificationSent_Title = "Views_Password_Reset_VerificationSent_Title",
            Views_Password_Reset_Reset_Message = "Views_Password_Reset_Reset_Message",
            Views_Password_Reset_Reset_Title = "Views_Password_Reset_Reset_Title",
            Views_Password_Reset_Finish_Message = "Views_Password_Reset_Finish_Message",
            Views_Password_Reset_Finish_Title = "Views_Password_Reset_Finish_Title",
            Views_Auth_SignIn_Title = "Views_Auth_SignIn_Title",
            Views_Submit = "Views_Submit",
            Model_ConfirmNewPassword = "Model_ConfirmNewPassword",
            Model_CurrentPassword = "Model_CurrentPassword",
            Model_Email = "Model_Email",
            Model_NewPassword = "Model_NewPassword",
            Model_Password = "Model_Password",
            Model_RememberMe = "Model_RememberMe",
            Model_ResetPasswordMessageSubject = "Model_ResetPasswordMessageSubject",
            Model_Username = "Model_Username",
            Model_NewEmail = "Model_NewEmail",
            Validation_EmailPattern = "Validation_EmailPattern",
            Validation_StringLength = "Validation_StringLength",
            Validation_StringLengthWithMin = "Validation_StringLengthWithMin",
            Model_EmailChangeNotificationMessageSubject = "Model_EmailChangeNotificationMessageSubject",
            Model_EmailChangeVerificationMessageSubject = "Model_EmailChangeVerificationMessageSubject",
            Model_EmailVerificationMessageSubject = "Model_EmailVerificationMessageSubject",
            Validation_NewEmailSameAsCurrent = "Validation_NewEmailSameAsCurrent",
            Links_ChangeEmail = "Links_ChangeEmail",
            Views_Email_Change_Change_Title = "Views_Email_Change_Change_Title",
            Views_Email_Change_Saved_Message = "Views_Email_Change_Saved_Message",
            Views_Email_Change_Saved_Title = "Views_Email_Change_Saved_Title",
            Views_GoTo = "Views_GoTo",
            Views_Email_Change_VerificationSent_Message = "Views_Email_Change_VerificationSent_Message",
            Views_Email_Change_VerificationSent_Title = "Views_Email_Change_VerificationSent_Title";
      }
   }
}
