//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Globalization;
using System.Web;

namespace MvcAccount {

   /// <summary>
   /// Provides access to localized strings used by MvcAccount.
   /// </summary>
   public static class AccountResources {
      
      /// <summary>
      /// Looks up a localized string similar to 'Change password'.
      /// </summary>
      public static string Links_ChangePassword { 
         get {
            return GetResource(Keys.Links_ChangePassword);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'My account'.
      /// </summary>
      public static string Links_Index { 
         get {
            return GetResource(Keys.Links_Index);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Can't access your account?'.
      /// </summary>
      public static string Links_Recovery { 
         get {
            return GetResource(Keys.Links_Recovery);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Sign in'.
      /// </summary>
      public static string Links_SignIn { 
         get {
            return GetResource(Keys.Links_SignIn);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Sign out'.
      /// </summary>
      public static string Links_SignOut { 
         get {
            return GetResource(Keys.Links_SignOut);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'The {1} is incorrect.'.
      /// </summary>
      public static string Validation_CurrentPasswordIncorrect { 
         get {
            return GetResource(Keys.Validation_CurrentPasswordIncorrect);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'User with email '{0}' already exists.'.
      /// </summary>
      public static string Validation_EmailAlreadyExists { 
         get {
            return GetResource(Keys.Validation_EmailAlreadyExists);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'You have reached the max. number of invalid attempts, you can try again in {0} minutes.'.
      /// </summary>
      public static string Validation_MaxInvalidSignInAttempts { 
         get {
            return GetResource(Keys.Validation_MaxInvalidSignInAttempts);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'We don't have your email address in our records, your request cannot be completed.'.
      /// </summary>
      public static string Validation_MissingEmail { 
         get {
            return GetResource(Keys.Validation_MissingEmail);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Cannot authenticate.'.
      /// </summary>
      public static string Validation_MissingPasswordCannotAuthenticate { 
         get {
            return GetResource(Keys.Validation_MissingPasswordCannotAuthenticate);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Passwords do not match.'.
      /// </summary>
      public static string Validation_PasswordsNotMatch { 
         get {
            return GetResource(Keys.Validation_PasswordsNotMatch);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Required field cannot be left blank.'.
      /// </summary>
      public static string Validation_Required { 
         get {
            return GetResource(Keys.Validation_Required);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Your account is disabled.'.
      /// </summary>
      public static string Validation_UserDisabled { 
         get {
            return GetResource(Keys.Validation_UserDisabled);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'User '{0}' does not exist.'.
      /// </summary>
      public static string Validation_UserNotExist { 
         get {
            return GetResource(Keys.Validation_UserNotExist);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to '{0} and password do not match.'.
      /// </summary>
      public static string Validation_UserPassNotMatch { 
         get {
            return GetResource(Keys.Validation_UserPassNotMatch);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Change password'.
      /// </summary>
      public static string Views_ChangePassword_Title { 
         get {
            return GetResource(Keys.Views_ChangePassword_Title);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Account options'.
      /// </summary>
      public static string Views_Index_Title { 
         get {
            return GetResource(Keys.Views_Index_Title);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Your password has been reset.'.
      /// </summary>
      public static string Views_PasswordReset_Message { 
         get {
            return GetResource(Keys.Views_PasswordReset_Message);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Password Reset'.
      /// </summary>
      public static string Views_PasswordReset_Title { 
         get {
            return GetResource(Keys.Views_PasswordReset_Title);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Your new password has been saved.'.
      /// </summary>
      public static string Views_PasswordSaved_Message { 
         get {
            return GetResource(Keys.Views_PasswordSaved_Message);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Password saved'.
      /// </summary>
      public static string Views_PasswordSaved_Title { 
         get {
            return GetResource(Keys.Views_PasswordSaved_Title);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'To reset your password, follow the instructions sent to your <strong>{0}</strong> email address.'.
      /// </summary>
      public static string Views_PasswordResetVerificationSent_Message { 
         get {
            return GetResource(Keys.Views_PasswordResetVerificationSent_Message);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Recovery Email Sent'.
      /// </summary>
      public static string Views_PasswordResetVerificationSent_Title { 
         get {
            return GetResource(Keys.Views_PasswordResetVerificationSent_Title);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'To reset your password, enter your {0}.'.
      /// </summary>
      public static string Views_ResetPassword_Message { 
         get {
            return GetResource(Keys.Views_ResetPassword_Message);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Forgot your password?'.
      /// </summary>
      public static string Views_ResetPassword_Title { 
         get {
            return GetResource(Keys.Views_ResetPassword_Title);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Select your new password and enter it below.'.
      /// </summary>
      public static string Views_RP_Message { 
         get {
            return GetResource(Keys.Views_RP_Message);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Reset Password'.
      /// </summary>
      public static string Views_RP_Title { 
         get {
            return GetResource(Keys.Views_RP_Title);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Sign in'.
      /// </summary>
      public static string Views_SignIn_Title { 
         get {
            return GetResource(Keys.Views_SignIn_Title);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Submit'.
      /// </summary>
      public static string Views_Submit { 
         get {
            return GetResource(Keys.Views_Submit);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Re-enter new password'.
      /// </summary>
      public static string Model_ConfirmNewPassword { 
         get {
            return GetResource(Keys.Model_ConfirmNewPassword);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Current password'.
      /// </summary>
      public static string Model_CurrentPassword { 
         get {
            return GetResource(Keys.Model_CurrentPassword);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Email'.
      /// </summary>
      public static string Model_Email { 
         get {
            return GetResource(Keys.Model_Email);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'New password'.
      /// </summary>
      public static string Model_NewPassword { 
         get {
            return GetResource(Keys.Model_NewPassword);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Password'.
      /// </summary>
      public static string Model_Password { 
         get {
            return GetResource(Keys.Model_Password);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Stay signed in'.
      /// </summary>
      public static string Model_RememberMe { 
         get {
            return GetResource(Keys.Model_RememberMe);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Password Assistance'.
      /// </summary>
      public static string Model_ResetPasswordMessageSubject { 
         get {
            return GetResource(Keys.Model_ResetPasswordMessageSubject);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Username'.
      /// </summary>
      public static string Model_Username { 
         get {
            return GetResource(Keys.Model_Username);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'New email address'.
      /// </summary>
      public static string Model_NewEmail { 
         get {
            return GetResource(Keys.Model_NewEmail);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'The {0} is invalid.'.
      /// </summary>
      public static string Validation_EmailPattern { 
         get {
            return GetResource(Keys.Validation_EmailPattern);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'The {0} cannot have more than {1} characters.'.
      /// </summary>
      public static string Validation_StringLength { 
         get {
            return GetResource(Keys.Validation_StringLength);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'The {0} must have between {2} and  {1} characters.'.
      /// </summary>
      public static string Validation_StringLengthWithMin { 
         get {
            return GetResource(Keys.Validation_StringLengthWithMin);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Email change notification'.
      /// </summary>
      public static string Model_EmailChangeNotificationMessageSubject { 
         get {
            return GetResource(Keys.Model_EmailChangeNotificationMessageSubject);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Email change verification'.
      /// </summary>
      public static string Model_EmailChangeVerificationMessageSubject { 
         get {
            return GetResource(Keys.Model_EmailChangeVerificationMessageSubject);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Email address verification'.
      /// </summary>
      public static string Model_EmailVerificationMessageSubject { 
         get {
            return GetResource(Keys.Model_EmailVerificationMessageSubject);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'The {1} must be different from the current one.'.
      /// </summary>
      public static string Validation_NewEmailSameAsCurrent { 
         get {
            return GetResource(Keys.Validation_NewEmailSameAsCurrent);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Change email address'.
      /// </summary>
      public static string Links_ChangeEmail { 
         get {
            return GetResource(Keys.Links_ChangeEmail);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Change email address'.
      /// </summary>
      public static string Views_ChangeEmail_Title { 
         get {
            return GetResource(Keys.Views_ChangeEmail_Title);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Your new email address has been saved.'.
      /// </summary>
      public static string Views_EmailSaved_Message { 
         get {
            return GetResource(Keys.Views_EmailSaved_Message);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Email saved'.
      /// </summary>
      public static string Views_EmailSaved_Title { 
         get {
            return GetResource(Keys.Views_EmailSaved_Title);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Go to {0}'.
      /// </summary>
      public static string Views_GoTo { 
         get {
            return GetResource(Keys.Views_GoTo);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'To confirm your email address change, follow the instructions sent to your <strong>{0}</strong> email address.'.
      /// </summary>
      public static string Views_EmailChangeVerificationSent_Message { 
         get {
            return GetResource(Keys.Views_EmailChangeVerificationSent_Message);
         }
      }
      
      /// <summary>
      /// Looks up a localized string similar to 'Verification Email Sent'.
      /// </summary>
      public static string Views_EmailChangeVerificationSent_Title { 
         get {
            return GetResource(Keys.Views_EmailChangeVerificationSent_Title);
         }
      }
      
      static string GetResource(string resourceKey) {

         CultureInfo culture = CultureInfo.CurrentUICulture;

         return GetUserResourceString(resourceKey, culture)
            ?? Resources.AccountResources.ResourceManager.GetString(resourceKey, culture);
      }

      static string GetUserResourceString(string resourceKey, CultureInfo culture) {

         string classKey = AccountConfiguration.Instance.ResourceClassKey;

         if (!classKey.HasValue())
            return null;

         return HttpContext.GetGlobalResourceObject(classKey, resourceKey, culture) as string;
      }
      
      internal static class Keys {
          public const string Links_ChangePassword = "Links_ChangePassword";
          public const string Links_Index = "Links_Index";
          public const string Links_Recovery = "Links_Recovery";
          public const string Links_SignIn = "Links_SignIn";
          public const string Links_SignOut = "Links_SignOut";
          public const string Validation_CurrentPasswordIncorrect = "Validation_CurrentPasswordIncorrect";
          public const string Validation_EmailAlreadyExists = "Validation_EmailAlreadyExists";
          public const string Validation_MaxInvalidSignInAttempts = "Validation_MaxInvalidSignInAttempts";
          public const string Validation_MissingEmail = "Validation_MissingEmail";
          public const string Validation_MissingPasswordCannotAuthenticate = "Validation_MissingPasswordCannotAuthenticate";
          public const string Validation_PasswordsNotMatch = "Validation_PasswordsNotMatch";
          public const string Validation_Required = "Validation_Required";
          public const string Validation_UserDisabled = "Validation_UserDisabled";
          public const string Validation_UserNotExist = "Validation_UserNotExist";
          public const string Validation_UserPassNotMatch = "Validation_UserPassNotMatch";
          public const string Views_ChangePassword_Title = "Views_ChangePassword_Title";
          public const string Views_Index_Title = "Views_Index_Title";
          public const string Views_PasswordReset_Message = "Views_PasswordReset_Message";
          public const string Views_PasswordReset_Title = "Views_PasswordReset_Title";
          public const string Views_PasswordSaved_Message = "Views_PasswordSaved_Message";
          public const string Views_PasswordSaved_Title = "Views_PasswordSaved_Title";
          public const string Views_PasswordResetVerificationSent_Message = "Views_PasswordResetVerificationSent_Message";
          public const string Views_PasswordResetVerificationSent_Title = "Views_PasswordResetVerificationSent_Title";
          public const string Views_ResetPassword_Message = "Views_ResetPassword_Message";
          public const string Views_ResetPassword_Title = "Views_ResetPassword_Title";
          public const string Views_RP_Message = "Views_RP_Message";
          public const string Views_RP_Title = "Views_RP_Title";
          public const string Views_SignIn_Title = "Views_SignIn_Title";
          public const string Views_Submit = "Views_Submit";
          public const string Model_ConfirmNewPassword = "Model_ConfirmNewPassword";
          public const string Model_CurrentPassword = "Model_CurrentPassword";
          public const string Model_Email = "Model_Email";
          public const string Model_NewPassword = "Model_NewPassword";
          public const string Model_Password = "Model_Password";
          public const string Model_RememberMe = "Model_RememberMe";
          public const string Model_ResetPasswordMessageSubject = "Model_ResetPasswordMessageSubject";
          public const string Model_Username = "Model_Username";
          public const string Model_NewEmail = "Model_NewEmail";
          public const string Validation_EmailPattern = "Validation_EmailPattern";
          public const string Validation_StringLength = "Validation_StringLength";
          public const string Validation_StringLengthWithMin = "Validation_StringLengthWithMin";
          public const string Model_EmailChangeNotificationMessageSubject = "Model_EmailChangeNotificationMessageSubject";
          public const string Model_EmailChangeVerificationMessageSubject = "Model_EmailChangeVerificationMessageSubject";
          public const string Model_EmailVerificationMessageSubject = "Model_EmailVerificationMessageSubject";
          public const string Validation_NewEmailSameAsCurrent = "Validation_NewEmailSameAsCurrent";
          public const string Links_ChangeEmail = "Links_ChangeEmail";
          public const string Views_ChangeEmail_Title = "Views_ChangeEmail_Title";
          public const string Views_EmailSaved_Message = "Views_EmailSaved_Message";
          public const string Views_EmailSaved_Title = "Views_EmailSaved_Title";
          public const string Views_GoTo = "Views_GoTo";
          public const string Views_EmailChangeVerificationSent_Message = "Views_EmailChangeVerificationSent_Message";
          public const string Views_EmailChangeVerificationSent_Title = "Views_EmailChangeVerificationSent_Title";
               
      }
   }
}
