//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAccount {

   static class Views {

      public const string 
         Web = "Web",
         _ViewStart = "_ViewStart";

      public static class Account {

         public const string 
            Index = "Index";
      }

      public static class Authentication {

         public const string 
            SignIn = "SignIn";

         public static class EditorTemplates {

            public const string 
               Object = "Object";
         }
      }

      public static class Email {

         public static class Change {

            public const string 
               Saved = "Saved",
               VerificationSent = "VerificationSent",
               _NotificationMessage = "_NotificationMessage",
               _NotificationMessage_es = "_NotificationMessage.es",
               _NotificationMessage_fi = "_NotificationMessage.fi",
               _NotificationMessage_pt = "_NotificationMessage.pt",
               _VerificationMessage = "_VerificationMessage",
               _VerificationMessage_es = "_VerificationMessage.es",
               _VerificationMessage_fi = "_VerificationMessage.fi",
               _VerificationMessage_pt = "_VerificationMessage.pt";

            public static class EditorTemplates {

               public const string 
                  Object = "Object";
            }
         }
      }

      public static class Password {

         public static class Change {

            public const string 
               Saved = "Saved";

            public static class EditorTemplates {

               public const string 
                  Object = "Object";
            }
         }

         public static class Reset {

            public const string 
               Done = "Done",
               Finish = "Finish",
               VerificationSent = "VerificationSent",
               _ErrorMessage = "_ErrorMessage",
               _ErrorMessage_es = "_ErrorMessage.es",
               _ErrorMessage_pt = "_ErrorMessage.pt",
               _VerificationMessage = "_VerificationMessage",
               _VerificationMessage_es = "_VerificationMessage.es",
               _VerificationMessage_fi = "_VerificationMessage.fi",
               _VerificationMessage_pt = "_VerificationMessage.pt";

            public static class EditorTemplates {

               public const string 
                  Object = "Object";
            }
         }
      }

      public static class Shared {

         public static class EditorTemplates {

            public const string 
               Object = "Object";
         }
      }
   }
}

