//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAccount {
		
    

 static class Views {
   
   
    

public static class Account {
   
    public const string ChangeEmail = "ChangeEmail"; 
    public const string ChangePassword = "ChangePassword"; 
    public const string EmailChangeVerificationSent = "EmailChangeVerificationSent"; 
    public const string EmailSaved = "EmailSaved"; 
    public const string Index = "Index"; 
    public const string PasswordReset = "PasswordReset"; 
    public const string PasswordResetVerificationSent = "PasswordResetVerificationSent"; 
    public const string PasswordSaved = "PasswordSaved"; 
    public const string ResetPassword = "ResetPassword"; 
    public const string RP = "RP"; 
    public const string SignIn = "SignIn"; 
   
    

public static class EditorTemplates {
   
    public const string Object = "Object"; 
    public const string Password = "Password"; 
   
   }
      
 

public static class Notifications {
   
    public const string EmailChangeNotificationMessage = "EmailChangeNotificationMessage"; 
    public const string EmailChangeNotificationMessage_es = "EmailChangeNotificationMessage.es"; 
    public const string EmailChangeNotificationMessage_fi = "EmailChangeNotificationMessage.fi"; 
    public const string EmailChangeVerificationMessage = "EmailChangeVerificationMessage"; 
    public const string EmailChangeVerificationMessage_es = "EmailChangeVerificationMessage.es"; 
    public const string EmailChangeVerificationMessage_fi = "EmailChangeVerificationMessage.fi"; 
    public const string EmailVerificationMessage = "EmailVerificationMessage"; 
    public const string EmailVerificationMessage_es = "EmailVerificationMessage.es"; 
    public const string EmailVerificationMessage_fi = "EmailVerificationMessage.fi"; 
    public const string ResetPasswordErrorMessage = "ResetPasswordErrorMessage"; 
    public const string ResetPasswordErrorMessage_es = "ResetPasswordErrorMessage.es"; 
    public const string ResetPasswordMessage = "ResetPasswordMessage"; 
    public const string ResetPasswordMessage_es = "ResetPasswordMessage.es"; 
    public const string ResetPasswordMessage_fi = "ResetPasswordMessage.fi"; 
    public const string _ViewStart = "_ViewStart"; 
   
   }
      
}
      
}
      
}

